### ISSUE TITLE
I try compile to wasm, but failed.

### ISSUE THREAD

**Issue by kaneruan** [shssoichiro/oxipng#451]
ℹ️  Compiling your crate in development mode...

[INFO]: 🎯  Checking for the Wasm target...
[INFO]: 🌀  Compiling to Wasm...
   Compiling libdeflate-sys v0.10.0
The following warnings were emitted during compilation:

warning: In file included from libdeflate/lib/arm/cpu_features.c:38:
warning: In file included from libdeflate/lib/arm/../cpu_features_common.h:38:
warning: libdeflate/lib/arm/../lib_common.h:64:10: fatal error: 'string.h' file not found
warning: #include <string.h>
warning:          ^~~~~~~~~~
warning: 1 error generated.

error: failed to run custom build command for `libdeflate-sys v0.10.0`

Caused by:
  process didn't exit successfully: `/Users/ruansan/Development/kg/rust-projects/png-optimize/target/debug/build/libdeflate-sys-a95b79cdfa5005fb/build-script-build` (exit status: 1)
  --- stdout
  TARGET = Some("wasm32-unknown-unknown")
  OPT_LEVEL = Some("0")
  HOST = Some("x86_64-apple-darwin")
  CC_wasm32-unknown-unknown = None
  CC_wasm32_unknown_unknown = None
  TARGET_CC = None
  CC = None
  CFLAGS_wasm32-unknown-unknown = None
  CFLAGS_wasm32_unknown_unknown = None
  TARGET_CFLAGS = None
  CFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("true")
  running: "clang" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "--target=wasm32-unknown-unknown" "-I" "libdeflate" "-o" "/Users/ruansan/Development/kg/rust-projects/png-optimize/target/wasm32-unknown-unknown/debug/build/libdeflate-sys-c7005d76609b5c0d/out/lib/libdeflate/lib/arm/cpu_features.o" "-c" "libdeflate/lib/arm/cpu_features.c"
  cargo:warning=In file included from libdeflate/lib/arm/cpu_features.c:38:
  cargo:warning=In file included from libdeflate/lib/arm/../cpu_features_common.h:38:
  cargo:warning=libdeflate/lib/arm/../lib_common.h:64:10: fatal error: 'string.h' file not found
  cargo:warning=#include <string.h>
  cargo:warning=         ^~~~~~~~~~
  cargo:warning=1 error generated.
  exit status: 1

  --- stderr

  error occurred: Command "clang" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "--target=wasm32-unknown-unknown" "-I" "libdeflate" "-o" "/Users/ruansan/Development/kg/rust-projects/png-optimize/target/wasm32-unknown-unknown/debug/build/libdeflate-sys-c7005d76609b5c0d/out/lib/libdeflate/lib/arm/cpu_features.o" "-c" "libdeflate/lib/arm/cpu_features.c" with args "clang" did not execute successfully (status code exit status: 1).

Error: Compiling your crate to WebAssembly failed
Caused by: failed to execute `cargo build`: exited with exit status: 101
  full command: "cargo" "build" "--lib" "--target" "wasm32-unknown-unknown"

**Comment by kaneruan** [comment]
This is my Cargo.toml
```toml
[package]
name = "png-optimize"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
wasm-bindgen-futures = "0.4.24"
wasm-bindgen = { version = "0.2.78", features = ["serde-serialize"] }
js-sys = "0.3.55"
# The `console_error_panic_hook` crate provides better debugging of panics by
# logging them with `console.error`. This is great for development, but requires
# all the `std::fmt` and `std::panicking` infrastructure, so isn't great for
# code size when deploying.
# parallel
oxipng = { version = "6.0.1", features = ["binary"] }
console_error_panic_hook = { version = "0.1.6", optional = true }
md5 = "0.7.0"
serde = { version = "1.0", features = ["derive"] }

# `wee_alloc` is a tiny allocator for wasm that is only ~1K in code size
# compared to the default allocator's ~10K. It is slower than the default
# allocator, however.
#
# Unfortunately, `wee_alloc` requires nightly Rust when targeting wasm for now.

[dependencies.web-sys]
version = "0.3.54"
features = ['Window', 'Document', 'console']

```
